### ISSUE TITLE
Quick comments on the policy brief

### ISSUE THREAD

**Issue by herculeeza** [joezippy/OpenUBI#3]
- Actually basic income dates back before Thomas Paine, at least to Sir Thomas More in the 1500s.
- While the automation argument is a popular reason for advocating for a UBI, it is not the only reason, nor is it necessarily the most important. Depending on your audience, it could make sense to raise some macroeconomic arguments for UBI as well (UBI as seigniorage reform, helicopter money, etc). The note about how people may not want to pay taxes to fund UBI overlooks the possibility that some level of UBI may not require taxes in the first place.
- You state that the "use of biometric technology is essential" but do not precisely explain how it would be used. There's a whole host of security vulnerabilities with biometrics, and it is far from clear to me why or how to incorporate them into an identity system.
- One thing to be aware of with digital money is consumer privacy. Allowing people the option to withdraw their funds in cash is a really important feature for this reason.

**Comment by joezippy** [comment]
Great points... Thank you!  

I'll try to address them one at a time here, having additional dialog with the core team:

1. Before Sr Thomas More -- https://basicincome.org/basic-income/history/
2. Impact other than automation - Macroeconomics and velocity of money within local communities, additional tax collection might not be needed
3. Biometric use is meant to be a little less precise, because some governments can leverage existing systems (China vs Ghana) or may want to put different biometric policies in place for UBI distribution... We really see this as a country, by country policy topic. That being said, our paper should clearly state multiple factor biometric information should be used for authentication and authorization of UBI payments leveraging a secure proven Identity Management System (IdM)
4. Agree and we'll try to make our intent regarding privacy more clear, beyond the unbanked and unconnected.

Please let me know if I missed something or you have additional comments.

**Comment by joezippy** [comment]
Topics have been incorporated in the the final version.
